### ISSUE TITLE
css世界

### ISSUE THREAD

**Issue by duzhihao-github** [duzhihao-github/blogs#10]
## width

这两个属性在英文下和中文下是不一样。中文以字为单位。英文以一个单词为单位。两个属性起作用的前提是有文字的子元素都是子元素的宽度最大的元素，否则父元素还是以最大宽度的元素的宽度为准。

* width:max-content 单词(字)是不会被换行。以文本总宽度为父元素的宽度，相当于`white-space: nowrap`。
* width:max-content 文本会被换行。以一个单词的宽度为父元素宽度

## max-width

max-系列的权重非常的高，甚至超越了!important

```css
p {
  width: 200px !important;
  max-width: 150px;
}
//最后还是显示的150px
```

```css
.container {
  min-width: 1400px;
  max-width: 1200px;
}
//这种情况遵守"最大原则",即实际为1400px;
```

max-与 min-主要是设置安全界限。在一个元素显示的动画的时候,元素的高度不能确定。我们就可以用 max-width 的方式。我们不需要给以具体高度值就可以实现这个效果。当然这样做的时候当高度达到实际高度是动画还没借宿。会有动画延迟的感觉。

```css
.element {
  max-height: 0;
  overflow: hidden;
  transition: max-height 0.25s;
}
.element.active {
  max-height: 666px; /* 一个足够大的最大高度值 */
}
```

## content attr

类似于`img`的 alt。

```css
.icon:before {
  content: attr(data-title);
}
```

## padding 与 margin

借助 background-clip 与 padding 实现三道杠的效果

```css
.icon-menu {
  display: inline-block;
  width: 140px;
  height: 10px;
  padding: 35px 0;
  border-top: 10px solid;
  border-bottom: 10px solid;
  background-color: currentColor;
  background-clip: content-box;
}
```

利用父级 margin 为负值实现图片两边对齐

```css
ul {
  margin-right: -20px;
}
ul > li {
  float: left;
  width: 100px;
  margin-right: 20px;
}
```

绝对定位一种垂直居中办法,这种还是需要固定高度和宽度。

```css
.father {
  width: 300px;
  height: 150px;
  position: relative;
}

.son {
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  width: 200px;
  height: 100px;
  margin: auto;
}
```

## border

因为 ie 下 border 设置虚线显示的是圆点。所有用这种方法可以再 ie 下实现一个圆。

```css
.box {
  width: 150px;
  height: 150px;
  /* 超出区域隐藏，只显示一个圆 */
  overflow: hidden;
}
.dotted {
  width: 100%;
  height: 100%;
  border: 149px dotted #cd0000;
}
```

三角形制作颜色设置顺序为上右下左，箭头朝向相反。

```css
div {
  width: 0;
  border: 10px solid;
  border-color: #f30 transparent transparent;
}
```

## ex

ex 是字体单位表示一个小写字母的高度。它和父元素的字号有关系，可以利用他实现文字和图标对其。

```css
.icon-arrow {
  display: inline-block;
  width: 20px;
  height: 1ex;
  background: url(arrow.png) no-repeat center;
}
// 这样就能实现当好和文字水平居中的效果。而且还不会受字号，页面高度的影响。
```

## vertical-align

利用 vertical-align 实现水平垂直居中

```html
<div id="container">
  <div id="dialog">....</div>
  <div id="assist"></div>
</div>
```

```css
#container {
  position: fixed;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  background: rgba(0, 0, 0, 0.5), none;
  text-align: center;
  white-space: nowrap;
  font-size: 0;
  z-index: 99;
}
#dialog {
  display: inline-block;
  vertical-align: middle;
}
#assist {
  display: inline-block;
  height: 100%;
  vertical-align: middle;
}
```

## BFC

触发 bfc 的一下情况，触发 bfc 就是内部元素完全和外部隔离，不会再影响到外部的布局。

* `<html>`根元素；
* float 的值不为 none；
* overflow 的值为 auto、scroll 或 hidden；
* display 的值为 table-cell、table-caption 和 inline-block 中的任何一个；
* position 的值不为 relative 和 static。

## overflow

滚动条是`html`的所以没必要拉着`body`一起设置`overflow:hidden`

下述代码是让`body`占据整个 window 的宽度。这样不会出现页面加载慢时导致居中元素偏移的问题。

```css
html {
  overflow-y: scroll; /* for IE8 */
}
:root {
  overflow-y: auto;
  overflow-x: hidden;
}
:root body {
  position: absolute;
}
body {
  width: 100vw;
  overflow: hidden;
}
```

## absolute

absolute 可以采用一种无依赖的布局方式。即不使用传统的子决父相的方式。不使用`left`和`top`控制，用 margin 或者 transform 来控制。

```css
.icon-warn {
  position: absolute;
  margin-left: -20px;
  width: 20px;
  height: 20px;
  background: url(warn.png) no-repeat center;
}
```

absolute 与 text-align 相配合实现水平居中，

虽然本示例中图片位置确实受 text-align 属性影响，但是并不是 text-align 和 absolute 元素直接发生关系，absolute 元素的 display 计算值是块状的，text-align 是不会有作用的。这里之所以产生了位置变化，本质上是“幽灵空白节点”和“无依赖绝对定位”共同作用的结果

当然我们是需要知道内联元素的宽度的。`margin-left`的值与负的一般宽度。与父元素`position:relative` 然后定位元素设置`left:50%`的方法类似。但不会有层级问题。

代码如下

```css
<p > <img src="1.jpg" > </p > p {
  text-align: center;
}
img {
  position: absolute;
  margin-left: ...;
}
```

absolute 与 overflow

> 如果 overflow 不是定位元素，同时绝对定位元素和 overflow 容器之间也没有定位元素，则
> overflow 无法对 absolute 元素进行剪裁。

根据上述所言。无依赖的`absolute`不会被父级的`overflow`所裁剪。

注意：由于 transform 在各个浏览器对`overflow`的支持不一样所以当元素还是被裁剪的话，试着找找是不是`transform`的原因

absolute 与流体自适应

当一个绝对定位元素的相对方向都有定位的时候该元素就会拥有一种和文档流相似的流体特性如

```CSS
.box {
position: absolute;
left: 0; right: 0;
}
```

当一个绝对定位元素有如下的设置就能覆盖整个浏览器。注意它的宽度高度是一种"格式化宽度/高度"，于`width:100%`完全不同。给与`margin`也不会出现超出屏幕。

```css
.box {
  position: absolute;
  left: 0;
  right: 0;
  top: 0;
  bottom: 0;
}
```

这种写法给与简单的实现水平居中的效果,如果有没有`left: 0; right: 0;`这种能够激发流体特性的属性就不会有这种剧居中效果。当然想要用`margin:auto auto`实现垂直水平居中是不能的。毕竟在标准文档流也没有这种效果。

```css
.element {
  width: 300px;
  height: 200px;
  position: absolute;
  left: 0;
  right: 0;
  top: 0;
  bottom: 0;
  margin: auto;
}
```

## fixed

fixed 实现在某个元素内的固定定位，方法还是利用无依赖利用 margin 进行布局。与绝对定位的无依赖一样不能使用`left`等定位属性。

```css
<div class="father" > <div class="son" > </div > </div > .father {
  width: 300px;
  height: 200px;
  position: relative;
}
.son {
  width: 40px;
  height: 40px;
  position: fixed;
  margin-left: -40px;
}
```

获取滚动条宽度实现完美的页面禁止滚动的效果

```js
//显示
var widthBar = 17,
  root = document.documentElement;
if (typeof window.innerWidth == "number") {
  widthBar = window.innerWidth - root.clientWidth;
}
root.style.overflow = "hidden";
root.style.borderRight = widthBar + "px solid transparent";
//隐藏
var root = document.documentElement;
root.style.overflow = "";
root.style.borderRight = "";
```

## z-index

`z-index`只有在 css2 中只对定位元素有用但是在 css3 中加入了对`flex`的支持

![-inde](C:\Users\DUDU-FE04\Desktop\z-index.png)

## font-size

```css
p {
  font-size: 16px;

  line-height: 1.5;
}

p > img {
  vertical-align: -25%;
  ||vertical-align: 0.6ex；;
}
```

子元素`vertical-align`使用百分比可以实现图标与文字居中的问题而且不受字体大小的影响，但是会受到行高的影响。如果是 ex 不仅可以实现而且不会受到行高的影响。

## text-decoration

在中文下`text-decoration`有可能与下一行的字出现重叠这时候我们用边框来作为下划线，边框不要设置颜色，它会默认的和字体一个颜色。

## 显示与隐藏

利用`visibility`和绝对定位来实现隐藏而且不占位置。或者透明度加绝对定位

```css
.hidden {
  position: absolute;
  visibility: hidden;
}

.opacity {
  position: absolute;
  opacity: 0;
  filter: Alpha(opacity=0);
}
```

visibility 与 display 的小区别

`visibility`的子元素会被隐藏但是如果设置了`visibility:visible`就会显现出来，但是`display:none`的元素就没有这样的效果。
